version: "3.2"

services:
  consul:
    image: ozlevka/consul
    networks:
      - consul
    ports:
      - "8500:8500"
    deploy:
      mode: global
    environment:
      - "CONSUL_BIND_INTERFACE=eth2"

networks:
  consul:
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.0.0/24